rules:
  use-trusted-publishing:
    ignore:
      # These are not real npm publish commands, but pnpm dlx pkg-pr-new publish
      # pkg-pr-new is a tool for creating preview deployments, not for publishing to npm
      - build-status.yml:210
      - build-status.yml:213
  cache-poisoning:
    ignore:
      # These are false positives - attestations ensure artifact integrity
      # setup-node actions in publish jobs followed by gh-release for attestation uploads
      - build-status.yml:644 # fast-check
      - build-status.yml:718 # ava
      - build-status.yml:792 # jest
      - build-status.yml:866 # packaged
      - build-status.yml:940 # poisoning
      - build-status.yml:1014 # vitest
      - build-status.yml:1088 # worker
  template-injection:
    ignore:
      # These are safe - TGZ_NAME is set from package.json version in controlled environment
      # bundle-path is output from attest-build-provenance action (trusted GitHub action)
      - build-status.yml:676 # fast-check
      - build-status.yml:750 # ava
      - build-status.yml:824 # jest
      - build-status.yml:898 # packaged
      - build-status.yml:972 # poisoning
      - build-status.yml:1046 # vitest
      - build-status.yml:1120 # worker
