rules:
  use-trusted-publishing:
    ignore:
      # These are not real npm publish commands, but pnpm dlx pkg-pr-new publish
      # pkg-pr-new is a tool for creating preview deployments, not for publishing to npm
      - build-status.yml:210
      - build-status.yml:213
  cache-poisoning:
    ignore:
      # These are false positives - attestations ensure artifact integrity
      # setup-node actions in publish jobs followed by gh-release for attestation uploads
      - build-status.yml:625 # fast-check
      - build-status.yml:699 # ava
      - build-status.yml:773 # jest
      - build-status.yml:847 # packaged
      - build-status.yml:921 # poisoning
      - build-status.yml:995 # vitest
      - build-status.yml:1069 # worker
  template-injection:
    ignore:
      # These are safe - TGZ_NAME is set from package.json version in controlled environment
      # bundle-path is output from attest-build-provenance action (trusted GitHub action)
      - build-status.yml:657 # fast-check
      - build-status.yml:731 # ava
      - build-status.yml:805 # jest
      - build-status.yml:879 # packaged
      - build-status.yml:953 # poisoning
      - build-status.yml:1027 # vitest
      - build-status.yml:1101 # worker
