rules:
  use-trusted-publishing:
    ignore:
      # These are not real npm publish commands, but pnpm dlx pkg-pr-new publish
      # pkg-pr-new is a tool for creating preview deployments, not for publishing to npm
      - build-status.yml:210
      - build-status.yml:213
  cache-poisoning:
    ignore:
      # These are false positives - attestations ensure artifact integrity
      # setup-node actions in publish jobs followed by gh-release for attestation uploads
      - build-status.yml:618 # fast-check
      - build-status.yml:692 # ava
      - build-status.yml:766 # jest
      - build-status.yml:840 # packaged
      - build-status.yml:914 # poisoning
      - build-status.yml:988 # vitest
      - build-status.yml:1062 # worker
      - build-status.yml:1136 # expect-type
  template-injection:
    ignore:
      # These are safe - TGZ_NAME is set from package.json version in controlled environment
      # bundle-path is output from attest-build-provenance action (trusted GitHub action)
      - build-status.yml:650 # fast-check
      - build-status.yml:724 # ava
      - build-status.yml:798 # jest
      - build-status.yml:872 # packaged
      - build-status.yml:946 # poisoning
      - build-status.yml:1020 # vitest
      - build-status.yml:1094 # worker
      - build-status.yml:1168 # expect-type
