enableGlobalCache: true
enableScripts: false
nodeLinker: pnp
enableHardenedMode: false
yarnPath: .yarn/releases/yarn-4.5.2.cjs

packageExtensions:
  '@docusaurus/theme-common@*':
    dependencies:
      '@docusaurus/plugin-content-docs': '*'
