packages:
  - examples
  - packages/*
  - website

blockExoticSubdeps: true

enableGlobalVirtualStore: true

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - unrs-resolver

linkWorkspacePackages: deep

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160
