packages:
  - examples
  - packages/*
  - website

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - unrs-resolver

trustPolicy: no-downgrade
trustPolicyExclude:
  - detect-port@1.6.1
  - rxjs@7.8.2
