packages:
  - examples
  - packages/*
  - website

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - unrs-resolver

trustPolicy: no-downgrade
trustPolicyExclude:
  - '@octokit/plugin-paginate-rest@9.2.2'
  - '@swc/core@1.13.3'
  - detect-port@1.6.1
  - rxjs@7.8.2
  - semver@6.3.1
  - undici@6.21.3
  - undici-types@6.21.0
