packages:
  - examples
  - packages/*
  - website
allowBuilds:
  '@swc/core': false
  core-js: false
  unrs-resolver: false

blockExoticSubdeps: true

enableGlobalVirtualStore: true

linkWorkspacePackages: deep

ignoredBuiltDependencies:
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - unrs-resolver

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 20160
