name: 🐛 Bug Report
description: Something not working as expected? Let us know!
labels: ['🐛 Bug Report']
body:
  - type: markdown
    attributes:
      value: Thanks for reporting this issue! 🙏 Bug reports help us make fast-check better for everyone.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior. A minimal reproduction (repo, snippet, or playground) is very helpful but not required.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Paste the output of the following command run at the root of your project:
        ```bash
        node -e "
          var l=['node: '+process.version];
          try{l.push('typescript: '+require('typescript/package.json').version)}catch{}
          try{l.push('fast-check: '+require('fast-check/package.json').version)}catch{}
          var p=['ava','jest','vitest','worker','poisoning'];
          p.forEach(function(s){try{l.push('@fast-check/'+s+': '+require('@fast-check/'+s+'/package.json').version)}catch{}});
          console.log(l.join('\n'))
        "
        ```
      render: text
    validations:
      required: false
