name: 🚀 Feature Request
description: Have an idea to improve fast-check? We'd love to hear it!
labels: ['🚀 Feature Request']
body:
  - type: markdown
    attributes:
      value: Thanks for suggesting a feature! 💡 Community ideas are what drive fast-check forward.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this feature be useful? What problem does it solve?
    validations:
      required: false
  - type: textarea
    id: example
    attributes:
      label: Example
      description: How would this feature be used in practice?
    validations:
      required: false
