import type { Arbitrary } from '../../../check/arbitrary/definition/Arbitrary.js';
import { String } from '../../../utils/globals.js';
import { boolean } from '../../boolean.js';
import { constant } from '../../constant.js';
import { double } from '../../double.js';
import type { StringConstraints } from '../../string.js';
import type { DepthSize } from './MaxLengthFromMinLength.js';
import type { ObjectConstraints } from './QualifiedObjectConstraints.js';

const safeJsonParse = JSON.parse;
const safeObjectIs = Object.is;

/** @internal */
function jsonDoubleArbitrary(): Arbitrary<number> {
  return double({ noDefaultInfinity: true, noNaN: true }).map(
    (v) => {
      // Ensure the generated double is exactly what JSON.parse would produce,
      // preventing subtle round-trip mismatches between String(v) and JSON.parse.
      // For -0, we preserve it directly as it is a valid JSON.parse output
      // but String(-0) returns "0" which would lose the sign.
      if (safeObjectIs(v, -0)) return v;
      return safeJsonParse(String(v)) as number;
    },
    (v) => v,
  );
}

/**
 * Shared constraints for:
 * - {@link json},
 * - {@link jsonValue},
 *
 * @remarks Since 2.5.0
 * @public
 */
export interface JsonSharedConstraints {
  /**
   * Limit the depth of the object by increasing the probability to generate simple values (defined via values)
   * as we go deeper in the object.
   *
   * @remarks Since 2.20.0
   */
  depthSize?: DepthSize;
  /**
   * Maximal depth allowed
   * @defaultValue Number.POSITIVE_INFINITY — _defaulting seen as "max non specified" when `defaultSizeToMaxWhenMaxSpecified=true`_
   * @remarks Since 2.5.0
   */
  maxDepth?: number;
  /**
   * Only generate instances having keys and values made of ascii strings (when true)
   * @deprecated Prefer using `stringUnit` to customize the kind of strings that will be generated by default.
   * @defaultValue true
   * @remarks Since 3.19.0
   */
  noUnicodeString?: boolean;
  /**
   * Replace the default unit for strings.
   * @defaultValue undefined
   * @remarks Since 3.23.0
   */
  stringUnit?: StringConstraints['unit'];
}

/**
 * Derive `ObjectConstraints` from a `JsonSharedConstraints`
 * @internal
 */

export function jsonConstraintsBuilder(
  stringArbitrary: Arbitrary<string>,
  constraints: JsonSharedConstraints,
): ObjectConstraints {
  const { depthSize, maxDepth } = constraints;
  const key = stringArbitrary;
  const values = [
    boolean(), // any boolean
    jsonDoubleArbitrary(), // any number valid in JSON
    stringArbitrary, // any string
    constant(null),
  ];
  return { key, values, depthSize, maxDepth };
}

/**
 * Typings for a Json array
 * @remarks Since 2.20.0
 * @public
 */
export type JsonArray = Array<JsonValue>;

/**
 * Typings for a Json object
 * @remarks Since 2.20.0
 * @public
 */
export type JsonObject = { [key in string]?: JsonValue };

/**
 * Typings for a Json value
 * @remarks Since 2.20.0
 * @public
 */
export type JsonValue = boolean | number | string | null | JsonArray | JsonObject;
