import { describe, it, expect, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import fc from '../../../src/fast-check.js';

const TargetNumExamples = 5;
const JsBlockStart = '```js';
const JsBlockEnd = '```';
const CommentForGeneratedValues = '// Examples of generated values:';
const CommentForArbitraryIndicator = '// Use the arbitrary:';
const CommentForStatistics = '// Computed statistics for 10k generated values:';

const allPathsFromWebsite = fs
  .globSync(`./website/docs/core-blocks/arbitraries/**/*.md`, {
    withFileTypes: true,
  })
  .filter((fileDescriptor) => fileDescriptor.isFile())
  .map((fileDescriptor, fileIndex) => ({
    filePath: path.join(fileDescriptor.parentPath, fileDescriptor.name),
    shortName: fileDescriptor.name,
    fileIndex,
  }));

export function declareDocsMdTests(shardIndex: number, shardCount: number): void {
  // Linked to https://github.com/vitest-dev/vitest/discussions/6511#discussioncomment-13145786
  afterEach(async () => {
    // already existing afterEach code goes here
    await new Promise((res) => setImmediate(res));
  });

  describe(`Docs.md (shard ${shardIndex + 1}/${shardCount})`, () => {
    if (process.env.SKIP_DOCUMENTATION === 'true') {
      it('should skip expensive tests', () => {});
      return;
    }
    if (process.env.UPDATE_CODE_SNIPPETS && shardIndex !== 0) {
      // Updating the snippets means writing the markdown files back: a single shard takes care of all of them,
      // concurrent partial updates of the same file from distinct workers would overwrite each others
      it('should delegate the update of code snippets to the first shard', () => {});
      return;
    }
    it.each(allPathsFromWebsite)(
      'should check code snippets validity and fix generated values on $shortName',
      ({ filePath, fileIndex }) => {
        // Each shard only re-executes (and re-checks) its own slice of the snippets, the others are preserved
        // as they appear in the committed documentation: together the shards re-check every snippet. The offset
        // based on fileIndex shifts the assignment from one file to the other so that the expensive snippets
        // (the statistics ones) of distinct files tend to land on distinct shards. Only balance is at stake
        // here: any assignment would preserve the coverage.
        const isOwnedUnit = process.env.UPDATE_CODE_SNIPPETS
          ? () => true
          : (unitIndex: number) => (2 * fileIndex + unitIndex) % shardCount === shardIndex;
        const originalFileContent = fs.readFileSync(filePath).toString();
        const { content: fileContent } = refreshContent(originalFileContent, isOwnedUnit);

        if (fileContent !== originalFileContent && process.env.UPDATE_CODE_SNIPPETS) {
          console.warn(`Updating code snippets defined in the documentation...`);
          fs.writeFileSync(filePath, fileContent);
        }
        if (!process.env.UPDATE_CODE_SNIPPETS) {
          try {
            expect(fileContent).toEqual(originalFileContent);
          } catch (err) {
            if (differsOnUnicodePropertySnippet(originalFileContent, fileContent)) {
              throw new Error(
                `Snippets relying on \\p{...} produced different values from the committed documentation. ` +
                  `Values generated by \\p{...} depend on the runtime's Unicode version, so this mismatch is ` +
                  `most likely caused by running the tests on a Node.js version different from the one that ` +
                  `produced the documentation. The committed docs were successfully generated with Node.js 24.14.1; ` +
                  `the current runtime is ${process.version}.`,
                { cause: err },
              );
            }
            throw err;
          }
        }
      },
    );
  });
}

// Helpers

function differsOnUnicodePropertySnippet(originalContent: string, refreshedContent: string): boolean {
  // Split both contents on "Examples of generated values:". In the resulting arrays,
  // chunk `i > 0` starts with the generated values produced by the code snippet at the
  // end of chunk `i - 1`. A `\p{...}` snippet differs when its associated values chunk
  // differs AND the preceding code chunk contains `\p{...}`.
  const separator = `\n${CommentForGeneratedValues}`;
  const originalChunks = originalContent.split(separator);
  const refreshedChunks = refreshedContent.split(separator);
  if (originalChunks.length !== refreshedChunks.length) {
    return false;
  }
  return originalChunks.some(
    (originalChunk, index) =>
      index !== 0 &&
      originalChunk !== refreshedChunks[index] &&
      /fc\.stringMatching\([^)]*\\[pP]\{/.test(refreshedChunks[index - 1]),
  );
}

function extractJsCodeBlocks(content: string): string[] {
  const lines = content.split('\n');
  const blocks: string[] = [];

  let isJsBlock = false;
  let currentBlock: string[] = [];
  for (const line of lines) {
    if (isJsBlock) {
      currentBlock.push(line);
      if (line === JsBlockEnd) {
        blocks.push(currentBlock.join('\n') + '\n');
        isJsBlock = false;
        currentBlock = [];
      }
    } else if (line === JsBlockStart) {
      blocks.push(currentBlock.join('\n') + '\n');
      isJsBlock = true;
      currentBlock = [line];
    } else {
      currentBlock.push(line);
    }
  }

  if (currentBlock.length !== 0) {
    blocks.push(currentBlock.join('\n'));
  }
  return blocks;
}

function isJsCodeBlock(blockContent: string): boolean {
  return blockContent.startsWith(`${JsBlockStart}\n`) && blockContent.endsWith(`${JsBlockEnd}\n`);
}

function trimJsCodeBlock(blockContent: string): string {
  const startLength = `${JsBlockStart}\n`.length;
  const endLength = `${JsBlockEnd}\n`.length;
  return blockContent.substr(startLength, blockContent.length - startLength - endLength);
}

function addJsCodeBlock(blockContent: string): string {
  return `${JsBlockStart}\n${blockContent}${JsBlockEnd}\n`;
}

function sanitizeNonCharacters(str: string): string {
  let result = '';
  for (const char of str) {
    const cp = char.codePointAt(0)!;
    // Unicode noncharacters: U+FDD0-U+FDEF and the last two code points of each plane
    // (U+FFFE, U+FFFF, U+1FFFE, U+1FFFF, ..., U+10FFFE, U+10FFFF).
    // These are permanently reserved and cause HTML parse errors.
    if ((cp >= 0xfdd0 && cp <= 0xfdef) || (cp & 0xffff) >= 0xfffe) {
      result += '\uFFFD';
    } else {
      result += char;
    }
  }
  return result;
}

function refreshContent(
  originalContent: string,
  isOwnedUnit: (unitIndex: number) => boolean,
): { content: string; numExecutedSnippets: number } {
  // Re-run the code (supported) snippets owned by the current shard
  // Re-generate the examples for them, and preserve the committed ones for the others

  let numExecutedSnippets = 0;
  let unitIndex = 0;

  // Extract code blocks
  const extractedBlocks = extractJsCodeBlocks(originalContent);

  // Execute code blocks
  const refinedBlocks = extractedBlocks.map((block) => {
    if (!isJsCodeBlock(block)) return block;

    // Remove list of examples and statistics, keeping the removed parts aside so that snippets owned by other
    // shards can be preserved as they were committed
    const strippedValues: string[] = [];
    const strippedStatistics: string[] = [];
    const cleanedBlock = trimJsCodeBlock(block)
      .replace(new RegExp(`${CommentForGeneratedValues}[^\n]*(\n//.*)*`, 'mg'), (stripped) => {
        strippedValues.push(stripped.substring(CommentForGeneratedValues.length));
        return CommentForGeneratedValues;
      })
      .replace(new RegExp(`${CommentForStatistics}[^\n]*(\n//.*)*`, 'mg'), (stripped) => {
        strippedStatistics.push(stripped.substring(CommentForStatistics.length));
        return CommentForStatistics;
      });

    // Extract code snippets
    const snippets = cleanedBlock
      .split(`\n${CommentForGeneratedValues}`)
      .map((snippet, index, all) => (index !== all.length - 1 ? `${snippet}\n${CommentForGeneratedValues}` : snippet));

    // Execute blocks and set examples
    const updatedSnippets = snippets.map((snippet) => {
      if (!snippet.endsWith(CommentForGeneratedValues)) return snippet;

      const committedValues = strippedValues.shift() ?? '';
      if (!isOwnedUnit(unitIndex++)) {
        return `${snippet}${committedValues}`;
      }
      ++numExecutedSnippets;

      // oxlint-disable-next-line no-unused-vars
      const generatedValues = (function (fc): string[] {
        const numRuns = 5 * TargetNumExamples;
        const lastIndexCommentForStatistics = snippet.lastIndexOf(CommentForStatistics);
        const refinedSnippet =
          lastIndexCommentForStatistics !== -1 ? snippet.substring(lastIndexCommentForStatistics) : snippet;
        const seed = refinedSnippet.replace(/\s*\/\/.*/g, '').replace(/\s+/gm, ' ').length;
        const indexArbitraryPart = refinedSnippet.indexOf(CommentForArbitraryIndicator);
        const preparationPart = indexArbitraryPart !== -1 ? refinedSnippet.substring(0, indexArbitraryPart) : '';
        const arbitraryPart = indexArbitraryPart !== -1 ? refinedSnippet.substring(indexArbitraryPart) : refinedSnippet;
        const santitizeArbitraryPart = arbitraryPart
          .trim()
          .replace(/;$/, '')
          .replace(/;\n\/\/.*$/m, '\n//');
        const evalCode = `${preparationPart}\nfc.sample(${santitizeArbitraryPart}\n, { numRuns: ${numRuns}, seed: ${seed} }).map(v => fc.stringify(v))`;
        try {
          return eval(evalCode);
        } catch (err) {
          throw new Error(`Failed to run code snippet:\n\n${evalCode}\n\nWith error message: ${err}`, {
            cause: err,
          });
        }
      })(fc);

      const uniqueGeneratedValues = Array.from(new Set(generatedValues.map(sanitizeNonCharacters))).slice(
        0,
        TargetNumExamples,
      );
      // If the display for generated values is too long, we split it into a list of items
      if (
        uniqueGeneratedValues.some((value) => value.includes('\n')) ||
        uniqueGeneratedValues.reduce((totalLength, value) => totalLength + value.length, 0) > 120
      ) {
        return `${snippet}${[...uniqueGeneratedValues, '…']
          .map((v) => `\n// • ${v.replace(/\n/gm, '\n//   ')}`)
          .join('')}`;
      } else {
        return `${snippet} ${uniqueGeneratedValues.join(', ')}…`;
      }
    });

    // Extract statistics snippets
    const statisticsSnippets = updatedSnippets
      .join('')
      .split(`\n${CommentForStatistics}`)
      .map((snippet, index, all) => (index !== all.length - 1 ? `${snippet}\n${CommentForStatistics}` : snippet));

    // Execute statistics
    const updatedStatisticsSnippets = statisticsSnippets.map((snippet) => {
      if (!snippet.endsWith(CommentForStatistics)) return snippet;

      const committedStatistics = strippedStatistics.shift() ?? '';
      if (!isOwnedUnit(unitIndex++)) {
        return `${snippet}${committedStatistics}`;
      }
      ++numExecutedSnippets;

      const computedStatitics = (baseSize: fc.Size) =>
        (function (fc): string[] {
          const lastIndexCommentForGeneratedValues = snippet.lastIndexOf(CommentForGeneratedValues);
          const refinedSnippet =
            lastIndexCommentForGeneratedValues !== -1 ? snippet.substring(lastIndexCommentForGeneratedValues) : snippet;
          const seed = refinedSnippet.replace(/\s*\/\/.*/g, '').replace(/\s+/gm, ' ').length;
          const evalCode = refinedSnippet;
          const originalConsoleLog = console.log;
          const originalGlobal = fc.readConfigureGlobal();
          try {
            const lines: string[] = [];
            console.log = (line) => lines.push(line);
            fc.configureGlobal({ seed, numRuns: 10000, baseSize });
            eval(evalCode);
            return lines;
          } catch (err) {
            throw new Error(`Failed to run code snippet:\n\n${evalCode}\n\nWith error message: ${err}`, { cause: err });
          } finally {
            console.log = originalConsoleLog;
            fc.configureGlobal(originalGlobal);
          }
        })(fc);
      const formatForSize = (size: fc.Size) =>
        `// For size = "${size}":\n${computedStatitics(size)
          .slice(0, TargetNumExamples)
          .map((line) => `// • ${line}`)
          .join('\n')}${computedStatitics.length > TargetNumExamples ? '\n// • …' : ''}`;
      const sizes = ['xsmall', 'small', 'medium'] as const;
      return `${snippet}\n${sizes.map((size) => formatForSize(size)).join('\n')}`;
    });

    return addJsCodeBlock(updatedStatisticsSnippets.join(''));
  });

  return { content: refinedBlocks.join(''), numExecutedSnippets };
}
