import { describe, it, expect } from 'vitest';
import fc from '../../src/fast-check.js';
import { asyncRunWithSanitizedStack } from './__test-helpers__/StackSanitizer.js';
import {
  IncreaseCommand,
  DecreaseCommand,
  EvenCommand,
  OddCommand,
  CheckLessThanCommand,
} from './model/CounterCommands.js';

const testFunc = (value: unknown) => {
  const repr = fc
    .stringify(value)
    .replace(/^(|Big)(Int|Uint|Float)(8|16|32|64)(|Clamped)Array\.from\((.*)\)$/, '$5')
    .replace(/__proto__:null,/g, '')
    .replace(/__proto__:null/g, '');
  for (let idx = 1; idx < repr.length; ++idx) {
    if (repr[idx - 1] === repr[idx] && repr[idx] !== '"' && repr[idx] !== '}') {
      return false;
    }
  }
  return true;
};

// Bumping from one patch of fast-check to another is not supposed
// to change the values that will be generated by the framework.
//
// Except in case of a real bug causing the arbitrary to be totally unusable.
//
// This suite checks this invariant stays true.
// Moreover, the framework should build consistent values throughout all the versions of node.
const settings = { seed: 42, verbose: 2 };

describe(`NoRegression`, () => {
  it('.filter', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.nat().filter((n) => n % 3 !== 0),
        (v) => testFunc(v),
      ),
    );
  });
  it('.map', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.nat().map((n) => String(n)),
        (v) => testFunc(v),
      ),
    );
  });
  it('.chain', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.nat(20).chain((n) => fc.clone(fc.nat(n), n)),
        (v) => testFunc(v),
      ),
    );
  });
  it('chainUntil', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.chainUntil(
          fc.nat().map((n): number[] => [n]),
          (tuple) => (tuple[tuple.length - 1] > 10 ? fc.nat().map((n) => [...tuple, n]) : undefined),
        ),
        (v) => testFunc(v),
      ),
    );
  });
  it('float', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.float(), (v) => testFunc(v)));
  });
  it('gen', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.gen(), (gen) => {
        const v1 = gen(fc.integer);
        const v2 = gen(fc.integer);
        return testFunc(`${v1}-${v2}`);
      }),
    );
  });
  it('double', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.double(), (v) => testFunc(v)));
  });
  it('integer', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.integer(), (v) => testFunc(v)));
  });
  it('nat', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.nat(), (v) => testFunc(v)));
  });
  it('maxSafeInteger', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.maxSafeInteger(), (v) => testFunc(v)));
  });
  it('maxSafeNat', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.maxSafeNat(), (v) => testFunc(v)));
  });
  it('string', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.string(), (v) => testFunc(v)));
  });
  it('stringMatching', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.stringMatching(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/), (v) => testFunc(v)),
    );
  });
  it('stringMatching({maxLength:10})', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.stringMatching(/^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/, { maxLength: 10 }), (v) =>
        testFunc(v),
      ),
    );
  });
  it('base64String', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.base64String(), (v) => testFunc(v)));
  });
  it('lorem', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.lorem(), (v) => testFunc(v)));
  });
  it('mapToConstant', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.mapToConstant({ num: 26, build: (v) => String.fromCharCode(v + 0x61) }),
        fc.mapToConstant({ num: 26, build: (v) => String.fromCharCode(v + 0x61) }),
        (a, b) => testFunc(a + b),
      ),
    );
  });
  it('option', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.option(fc.nat()), (v) => testFunc(v)));
  });
  it('oneof', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.oneof<any>(fc.nat(), fc.string({ unit: 'grapheme-ascii', minLength: 1, maxLength: 1 })),
        (v) => testFunc(v),
      ),
    );
  });
  it('oneof[weighted]', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.oneof<any>(
          { weight: 1, arbitrary: fc.nat() },
          { weight: 5, arbitrary: fc.string({ unit: 'grapheme-ascii', minLength: 1, maxLength: 1 }) },
        ),
        testFunc,
      ),
    );
  });
  it('clone', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.clone(fc.nat(), 2), (v) => testFunc(v)));
  });
  it('shuffledSubarray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.shuffledSubarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (v) =>
        testFunc(v.join('')),
      ),
    );
  });
  it('subarray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.subarray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (v) =>
        testFunc(v.join('')),
      ),
    );
  });
  it('array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.array(fc.nat()), (v) => testFunc(v)));
  });
  it('sparseArray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.sparseArray(fc.nat()),
        (v) =>
          // Sum of first element of each group should be less or equal to 10
          // If a group starts at index 0, the whole group is ignored
          Object.entries(v).reduce((acc, [index, cur]) => {
            if (index === '0' || v[Number(index) - 1] !== undefined) return acc;
            else return acc + cur;
          }, 0) <= 10,
      ),
    );
  });
  it('sparseArray({noTrailingHole:true})', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.sparseArray(fc.nat(), { noTrailingHole: true }),
        (v) =>
          // Sum of first element of each group should be less or equal to 10
          // If a group starts at index 0, the whole group is ignored
          Object.entries(v).reduce((acc, [index, cur]) => {
            if (index === '0' || v[Number(index) - 1] !== undefined) return acc;
            else return acc + cur;
          }, 0) <= 10,
      ),
    );
  });
  it('infiniteStream', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.infiniteStream(fc.nat()), (s) => testFunc([...s.take(10)])),
    );
  });
  it('infiniteStream (noHistory)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.infiniteStream(fc.nat(), { noHistory: true }), (s) => testFunc([...s.take(10)])),
    );
  });
  it('uniqueArray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uniqueArray(fc.nat()), (v) => testFunc(v)));
  });
  it('uniqueArray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uniqueArray(fc.nat()), (v) => testFunc(v)));
  });
  it('tuple', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.tuple(fc.nat(), fc.nat()), (v) => testFunc(v)),
    );
  });
  it('limitShrink', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.limitShrink(fc.nat(), 4), (v) => testFunc(v)));
  });
  it('int8Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.int8Array(), (v) => testFunc(v)));
  });
  it('uint8Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uint8Array(), (v) => testFunc(v)));
  });
  it('uint8ClampedArray', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uint8ClampedArray(), (v) => testFunc(v)));
  });
  it('int16Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.int16Array(), (v) => testFunc(v)));
  });
  it('uint16Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uint16Array(), (v) => testFunc(v)));
  });
  it('int32Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.int32Array(), (v) => testFunc(v)));
  });
  it('uint32Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uint32Array(), (v) => testFunc(v)));
  });
  it('float32Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.float32Array(), (v) => testFunc(v)));
  });
  it('float64Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.float64Array(), (v) => testFunc(v)));
  });
  it('record', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.record({ k1: fc.nat(), k2: fc.nat() }, { requiredKeys: [] }), (v) => testFunc(v)),
    );
  });
  it('dictionary', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.dictionary(fc.string(), fc.nat()), (v) => testFunc(v)),
    );
  });
  it('anything', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.anything(), (v) => testFunc(v)));
  });
  it('object', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.object(), (v) => testFunc(v)));
  });
  it('json', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.json(), (v) => testFunc(v)));
  });
  it('jsonValue', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.jsonValue(), (v) => testFunc(v)));
  });
  it('compareFunc', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.compareFunc(), (f) => testFunc(f(1, 2))));
  });
  it('func', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.func(fc.nat()), (f) => testFunc(f())));
  });
  it('ipV4', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.ipV4(), (v) => testFunc(v)));
  });
  it('ipV4Extended', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.ipV4Extended(), (v) => testFunc(v)));
  });
  it('ipV6', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.ipV6(), (v) => testFunc(v)));
  });
  it('domain', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.domain(), (v) => testFunc(v)));
  });
  it('webAuthority', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webAuthority(), (v) => testFunc(v)));
  });
  it('webSegment', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webSegment(), (v) => testFunc(v)));
  });
  it('webFragments', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webFragments(), (v) => testFunc(v)));
  });
  it('webQueryParameters', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webQueryParameters(), (v) => testFunc(v)));
  });
  it('webPath', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webPath(), (v) => testFunc(v)));
  });
  it('webUrl', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.webUrl(), (v) => testFunc(v)));
  });
  it('emailAddress', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.emailAddress(), (v) => testFunc(v)));
  });
  it('date', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.date(), (v) => testFunc(v)));
  });
  it('ulid', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.ulid(), (v) => testFunc(v)));
  });
  it('uuid', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.uuid(), (v) => testFunc(v)));
  });
  it('letrec', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.letrec((tie) => ({
          // Trick to be able to shrink from node to leaf
          tree: fc.nat(1).chain((id) => (id === 0 ? tie('leaf') : tie('node'))),
          node: fc.record({ left: tie('tree'), right: tie('tree') }),
          leaf: fc.nat(21),
        })).tree,
        (v) => testFunc(v),
      ),
    );
  });
  it('letrec (oneof:maxDepth)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.letrec((tie) => ({
          tree: fc.oneof({ withCrossShrink: true, maxDepth: 2 }, tie('leaf'), tie('node')),
          node: fc.record({ a: tie('tree'), b: tie('tree'), c: tie('tree') }),
          leaf: fc.nat(21),
        })).tree,
        (v) => testFunc(v),
      ),
    );
  });
  it('letrec (oneof:depthSize)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.letrec((tie) => ({
          tree: fc.oneof({ withCrossShrink: true, depthSize: 'small' }, tie('leaf'), tie('node')),
          node: fc.record({ a: tie('tree'), b: tie('tree'), c: tie('tree') }),
          leaf: fc.nat(21),
        })).tree,
        (v) => testFunc(v),
      ),
    );
  });
  it('commands', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.commands([
          fc.nat().map((n) => new IncreaseCommand(n)),
          fc.nat().map((n) => new DecreaseCommand(n)),
          fc.constant(new EvenCommand()),
          fc.constant(new OddCommand()),
          fc.nat().map((n) => new CheckLessThanCommand(n + 1)),
        ]),
        (cmds) => {
          const setup = () => ({
            model: { count: 0 },
            real: {},
          });
          try {
            fc.modelRun(setup, cmds);
            return true;
          } catch {
            return false;
          }
        },
      ),
    );
  });
  it('context', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.context(), fc.nat(), (ctx, v) => {
        ctx.log(`Value was ${v}`);
        return testFunc(v);
      }),
    );
  });

  it('Promise<number>', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        fc.integer().map((v) => [v, Promise.resolve(v)] as const),
        ([v, _p]) => testFunc(v),
      ),
    );
  });
  it('user defined examples', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.string(), (v) => testFunc(v)),
      { ...settings, examples: [['hi'], ['hello'], ['hey']] },
    );
  });
  it('user defined examples (including not shrinkable values)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(
        // Shrinkable: built-in
        fc.nat(),
        // Cannot shrinking: missing unmapper
        fc.nat().map((v) => String(v)),
        // Shrinkable: unmapper provided
        fc.nat().map(
          (v) => String(v),
          (v) => Number(v),
        ),
        // Shrinkable: filter can shrink given the value to shrink matches the predicate
        fc.nat().filter((v) => v % 2 === 0),
        (a, b, c, d) => testFunc([a, b, c, d]),
      ),
      {
        ...settings,
        examples: [
          [1, '2', '3', 4],
          [5, '6', '7', 8],
          [9, '10', '11', 12],
          [13, '14', '15', 16],
          [17, '18', '19', 20],
        ],
      },
    );
  });
  it('bigInt', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.bigInt(), (v) => testFunc(v)));
  });
  it('bigInt({min})', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.bigInt({ min: BigInt(1) << BigInt(16) }), (v) => testFunc(v)),
    );
  });
  it('bigInt({max})', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.bigInt({ max: BigInt(1) << BigInt(64) }), (v) => testFunc(v)),
    );
  });
  it('bigInt({min, max})', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.bigInt({ min: BigInt(1) << BigInt(16), max: BigInt(1) << BigInt(64) }), (v) => testFunc(v)),
    );
  });
  it('bigInt64Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.bigInt64Array(), (v) => testFunc(v)));
  });
  it('bigUint64Array', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.bigUint64Array(), (v) => testFunc(v)));
  });
  it('mixedCase', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.mixedCase(fc.constant('cCbAabBAcaBCcCACcABaCAaAabBACaBcBb')), (v) => testFunc(v)),
    );
  });
  it('mixedCase(string(constantFrom))', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.mixedCase(fc.string({ unit: fc.constantFrom('a', 'b', 'c') })), (v) => testFunc(v)),
    );
  });
});

describe(`NoRegression (async)`, () => {
  const asyncNumber = fc.integer().map((v) => Promise.resolve(v));

  it('scheduler', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.scheduler(), async (s) => {
        const received = [] as string[];
        for (const v of ['a', 'b', 'c']) {
          s.schedule(Promise.resolve(v)).then((out) => {
            received.push(out);
            s.schedule(Promise.resolve(out.toUpperCase())).then((out2) => {
              received.push(out2);
            });
          });
        }
        await s.waitAll();
        return !received.join('').includes('aBc');
      }),
    );
  });
  it('number', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(fc.integer(), async (v) => testFunc(v)));
  });

  it('.map (to Promise)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(fc.asyncProperty(asyncNumber, async (v) => testFunc(await v)));
  });

  it('func (to Promise)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.func(asyncNumber), async (f) => testFunc(await f())),
    );
  });

  it('infiniteStream (to Promise)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.infiniteStream(asyncNumber), async (s) => testFunc(await Promise.all([...s.take(10)]))),
    );
  });

  it('infiniteStream (noHistory) (to Promise)', async () => {
    await expectPropertyToThrowErrorMatchingSnapshot(
      fc.asyncProperty(fc.infiniteStream(asyncNumber, { noHistory: true }), async (s) =>
        testFunc(await Promise.all([...s.take(10)])),
      ),
    );
  });
});

// Helpers

async function expectPropertyToThrowErrorMatchingSnapshot<T>(
  property: fc.IAsyncPropertyWithHooks<T>,
  customSettings?: fc.Parameters<T>,
) {
  await expect(
    asyncRunWithSanitizedStack(async () => await fc.assert(property, customSettings ?? settings)),
  ).rejects.toThrowErrorMatchingSnapshot();
}
