name: 'Install dependencies but use current build for fast-check'
description: 'Install dependencies but use current build for fast-check'
inputs:
  path:
    description: 'Directory path'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        PROJECT_ROOT_PATH="$(pwd)"
        cd "${{inputs.path}}"
        echo "ℹ️ Install dependencies..."
        yarn --frozen-lockfile
        echo "ℹ️ Install current build for fast-check..."
        yarn add "file:$PROJECT_ROOT_PATH/fast-check.tgz"
        echo "ℹ️ Revert local changes..."
        git checkout -- package.json
        git checkout -- yarn.lock
      shell: bash
    - run: |
        echo "ℹ️ Print fast-check (tgz)..."
        mkdir bundle
        tar -C bundle -zxvf fast-check.tgz
        cd bundle/package
        cat "lib/fast-check-default.js"
      shell: bash
    - run: |
        echo "ℹ️ Print git context..."
        git --no-pager log --decorate=short --pretty=oneline -n10
        echo "ℹ️ Print env context..."
        echo $GITHUB_SHA
        echo "ℹ️ Print..."
        ls -alh "${{inputs.path}}/node_modules/"
        echo "ℹ️ Print fast-check..."
        cat "${{inputs.path}}/node_modules/fast-check/lib/fast-check-default.js"
        echo "ℹ️ Check version of fast-check..."
        node .github/actions/install-deps-with-current-fc/check-hash.js "${{inputs.path}}/node_modules/fast-check"
      shell: bash