name: 'Install dependencies but use current build for fast-check'
description: 'Install dependencies but use current build for fast-check'
inputs:
  package:
    description: 'Name of the package'
    required: true
  path:
    description: 'Directory path'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        echo "ℹ️ Install current build for fast-check..."
        yarn workspace "${{inputs.package}}" add "fast-check@$(pwd)/packages/fast-check/package.tgz"
      shell: bash
    - run: |
        echo "ℹ️ Copy script..."
        cp .github/actions/install-deps-with-current-fc/check-hash.cjs "${{inputs.path}}/check-hash-$GITHUB_SHA.cjs"
        echo "ℹ️ Check version of fast-check..."
        cd "${{inputs.path}}"
        node check-hash-*.cjs
        echo "ℹ️ Remove script..."
        rm "check-hash-$GITHUB_SHA.cjs"
      shell: bash
