name: "Install dependencies but use current build for fast-check"
description: "Install dependencies but use current build for fast-check"
inputs:
  package:
    description: "Name of the package"
    required: true
  path:
    description: "Directory path"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        PROJECT_ROOT_PATH="$(pwd)"
        cd "${{inputs.path}}"
        echo "ℹ️ Clean yarn cache entry for fast-check (if any)..."
        yarn cache clean fast-check
        echo "ℹ️ Install dependencies..."
        yarn --immutable
        echo "ℹ️ Clean yarn cache entry for fast-check..."
        yarn cache clean fast-check
        echo "ℹ️ Install current build for fast-check..."
        yarn workspace "${{inputs.package}}" add "file:$PROJECT_ROOT_PATH/fast-check.tgz"
        echo "ℹ️ Clean yarn cache entry for fast-check..."
        yarn cache clean fast-check
        echo "ℹ️ Revert local changes..."
        git checkout -- package.json
        git checkout -- yarn.lock
      shell: bash
    - run: |
        echo "ℹ️ Copy script..."
        cp .github/actions/install-deps-with-current-fc/check-hash.cjs "${{inputs.path}}/check-hash-$GITHUB_SHA.cjs"
        echo "ℹ️ Check version of fast-check..."
        cd "${{inputs.path}}"
        node check-hash-*.cjs
        echo "ℹ️ Remove script..."
        rm "check-hash-$GITHUB_SHA.cjs"
      shell: bash
