import { Arbitrary } from '../check/arbitrary/definition/Arbitrary';
import { BigInt } from '../utils/globals';
import { constantFrom } from './constantFrom';

/**
 * Constraints to be applied on {@link falsy}
 * @remarks Since 1.26.0
 * @public
 */
export interface FalsyContraints {
  /**
   * Enable falsy bigint value
   * @remarks Since 1.26.0
   */
  withBigInt?: boolean;
}

/**
 * Typing for values generated by {@link falsy}
 * @remarks Since 2.2.0
 * @public
 */
// eslint-disable-next-line @typescript-eslint/ban-types
export type FalsyValue<TConstraints extends FalsyContraints = {}> =
  | false
  | null
  | 0
  | ''
  | typeof NaN
  | undefined
  | HTMLAllCollection
  | (TConstraints extends { withBigInt: true } ? 0n : never);

const allDefaultFalsyValuesBase: FalsyValue[] = [false, null, undefined, 0, '', NaN];
const allDefaultFalsyValues: FalsyValue[] =
  typeof document !== 'undefined' && document.all !== undefined
    ? [...allDefaultFalsyValuesBase, document.all]
    : allDefaultFalsyValuesBase;

/**
 * For falsy values:
 * - ''
 * - 0
 * - NaN
 * - false
 * - null
 * - undefined
 * - 0n (whenever withBigInt: true)
 *
 * @param constraints - Constraints to apply when building instances
 *
 * @remarks Since 1.26.0
 * @public
 */
export function falsy<TConstraints extends FalsyContraints>(
  constraints?: TConstraints
): Arbitrary<FalsyValue<TConstraints>> {
  if (!constraints || !constraints.withBigInt) {
    return constantFrom<FalsyValue[]>(...allDefaultFalsyValues);
  }
  return constantFrom<FalsyValue<TConstraints>[]>(...allDefaultFalsyValues, BigInt(0) as any);
}
