name: 'Install with published bundle'
description: 'Install dependencies with published bundle'
inputs:
  path:
    description: 'Path to the directory to be installed'
runs:
  using: 'composite'
  steps:
    - name: Install default dependencies
      run: |
        cd ${{inputs.path}}
        yarn --frozen-lockfile
      shell: bash
    - name: Replace fast-check by production package
      run: |
        PROJECT_ROOT_PATH="$(pwd)"
        cd ${{inputs.path}}
        yarn add "$PROJECT_ROOT_PATH/fast-check.tgz"
        git checkout -- package.json
        git checkout -- yarn.lock
      shell: bash
    - name: Check setup
      run: |
        node .github/actions/install-with-bundle/check-hash.js "${{inputs.path}}/node_modules/fast-check"
      shell: bash