name: 'Install with published bundle'
description: 'Install dependencies with published bundle'
inputs:
  path:
    description: 'Path to the directory to be installed'
runs:
  using: 'composite'
  steps:
    - name: Install default dependencies
      run: |
        cd ${{inputs.path}}
        yarn --frozen-lockfile
      shell: bash
    - name: Replace fast-check by production package
      run: |
        cd ${{inputs.path}}
        yarn add ../fast-check.tgz
        git checkout -- package.json
        git checkout -- yarn.lock
      shell: bash
    - name: Check setup
      run: |
        true
      shell: bash