import type { RandomGenerator } from 'pure-rand/types/RandomGenerator';

import { Random } from '../../random/generator/Random.js';
import type { IRawProperty } from '../property/IRawProperty.js';
import { Value } from '../arbitrary/definition/Value.js';
import { safeMap } from '../../utils/globals.js';
import type { QualifiedRandomGenerator } from './configuration/QualifiedParameters.js';
import { adaptRandomGenerator } from '../../random/generator/RandomGenerator.js';
import { FastXorshift128Plus } from '../../random/generator/FastXorshift128Plus.js';

/**
 * Sentinel returned by hot-path pullers (such as {@link TossIterator.pullNext}
 * and {@link RunnerIterator.pullNext}) to signal end-of-iteration without
 * allocating an `{ done: true }` IteratorResult per call.
 *
 * @internal
 */
export const SENTINEL_DONE: unique symbol = Symbol('SENTINEL_DONE');
const DONE_RESULT: IteratorResult<never> = { value: undefined, done: true };

/**
 * Interface implemented by iterators that expose a hot-path puller returning
 * the value directly (or {@link SENTINEL_DONE}) instead of an IteratorResult.
 *
 * @internal
 */
export interface PullableIterator<Ts> extends IterableIterator<Ts> {
  pullNext(): Ts | typeof SENTINEL_DONE;
}

/**
 * Adapter wrapping any IterableIterator so that it presents the
 * {@link PullableIterator} interface. Used to keep the `nextValues` slot in
 * {@link RunnerIterator} monomorphic: shrink streams flow through the adapter
 * so the slot always holds a class instance with `pullNext`.
 *
 * @internal
 */
export class PullableAdapter<Ts> implements PullableIterator<Ts> {
  constructor(private readonly it: IterableIterator<Ts>) {}
  [Symbol.iterator](): IterableIterator<Ts> {
    return this;
  }
  next(): IteratorResult<Ts> {
    return this.it.next();
  }
  pullNext(): Ts | typeof SENTINEL_DONE {
    const n = this.it.next();
    return n.done ? SENTINEL_DONE : n.value;
  }
}

/**
 * Iterator yielding the values consumed by the runner.
 *
 * Walks `examples` first (already-known values supplied by the user), then
 * produces an unbounded stream of values generated by `generator` from the
 * seeded rng.
 *
 * Reuses a single {@link Random} wrapper between iterations to avoid the
 * per-iteration wrapper allocation that the previous generator-based `toss`
 * incurred. Fields are eagerly initialized so V8 sees stable monomorphic shapes.
 *
 * @internal
 */
class TossIterator<Ts> implements PullableIterator<Value<Ts>> {
  private readonly generator: IRawProperty<Ts>;
  private readonly examples: Ts[];
  private readonly rng: QualifiedRandomGenerator;
  private readonly mrng: Random;
  // When both rng and the mrng's internal rng are FastXorshift128Plus instances
  // we can sync their state in place per iteration (4 field assignments) and
  // skip the `clone()` allocation entirely. These two fields hold the typed
  // refs when the fast path is available.
  private readonly fastRng: FastXorshift128Plus | undefined;
  private readonly fastWork: FastXorshift128Plus | undefined;
  private exampleIdx: number;
  private idx: number;
  constructor(
    generator: IRawProperty<Ts>,
    seed: number,
    random: (seed: number) => QualifiedRandomGenerator,
    examples: Ts[],
  ) {
    this.generator = generator;
    this.examples = examples;
    const rng = random(seed);
    this.rng = rng;
    this.mrng = new Random(rng);
    if (rng instanceof FastXorshift128Plus) {
      const work = this.mrng.unsafeGetInternal();
      if (work instanceof FastXorshift128Plus) {
        this.fastRng = rng;
        this.fastWork = work;
      } else {
        this.fastRng = undefined;
        this.fastWork = undefined;
      }
    } else {
      this.fastRng = undefined;
      this.fastWork = undefined;
    }
    this.exampleIdx = 0;
    this.idx = 0;
  }
  [Symbol.iterator](): IterableIterator<Value<Ts>> {
    return this;
  }
  next(): IteratorResult<Value<Ts>> {
    const v = this.pullNext();
    if (v === SENTINEL_DONE) return DONE_RESULT;
    return { value: v, done: false };
  }
  /**
   * Hot-path: returns the next {@link Value} directly. This iterator is
   * unbounded once examples are exhausted, so it never actually returns
   * {@link SENTINEL_DONE} — the wider return type satisfies the
   * {@link PullableIterator} contract so consumers can stay monomorphic.
   * Skips the `{ value, done }` allocation that the standard iterator
   * protocol forces.
   * @internal
   */
  pullNext(): Value<Ts> | typeof SENTINEL_DONE {
    const exampleIdx = this.exampleIdx;
    const examples = this.examples;
    if (exampleIdx < examples.length) {
      this.exampleIdx = exampleIdx + 1;
      return new Value(examples[exampleIdx], undefined);
    }
    const fastRng = this.fastRng;
    if (fastRng !== undefined) {
      // Fast path: jump the pool rng, then copy its state into the work rng
      // without allocating a fresh instance.
      fastRng.jump();
      // oxlint-disable-next-line typescript/no-non-null-assertion
      fastRng.unsafeCopyStateTo(this.fastWork!);
    } else {
      const rng = this.rng;
      rng.jump();
      // Generic fallback: clone the post-jump pool rng and reinstall it so the
      // predicate may freely mutate without leaking back into the seed sequence.
      this.mrng.unsafeReplaceInternal(rng.clone() as QualifiedRandomGenerator);
    }
    const v = this.generator.generate(this.mrng, this.idx);
    this.idx = this.idx + 1;
    return v;
  }
}

/** @internal */
export function toss<Ts>(
  generator: IRawProperty<Ts>,
  seed: number,
  random: (seed: number) => QualifiedRandomGenerator,
  examples: Ts[],
): PullableIterator<Value<Ts>> {
  return new TossIterator(generator, seed, random, examples);
}

/** @internal */
function lazyGenerate<Ts>(generator: IRawProperty<Ts>, rng: RandomGenerator, idx: number): () => Value<Ts> {
  return () => generator.generate(new Random(rng), idx);
}

/** @internal */
export function* lazyToss<Ts>(
  generator: IRawProperty<Ts>,
  seed: number,
  random: (seed: number) => RandomGenerator,
  examples: Ts[],
): IterableIterator<() => Value<Ts>> {
  yield* safeMap(examples, (e) => () => new Value(e, undefined));
  let idx = 0;
  const rng = adaptRandomGenerator(random(seed));
  for (;;) {
    rng.jump();
    yield lazyGenerate(generator, rng, idx++);
  }
}
