name: Fix pnpm lock conflicts PR

on:
  workflow_dispatch:
    inputs:
      ref_value:
        description: 'PR number'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: read

jobs:
  fix-pnpm-lock:
    name: 'Fix pnpm lock conflicts and commit changes'
    runs-on: ubuntu-latest
    steps:
      - name: Determine checkout reference
        id: ref
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          HEAD_BRANCH=$(gh pr view "${{ github.event.inputs.ref_value }}" --json headRefName --repo ${{ github.repository }} | jq -r '.headRefName')
          echo "ref=$HEAD_BRANCH" >> $GITHUB_OUTPUT

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ steps.ref.outputs.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Using Node v24.x
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24.x'
          cache: 'pnpm'

      - name: Check current branch info
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Target PR: ${{ github.event.inputs.ref_value }}"

      - name: Check if pnpm-lock.yaml exists
        id: lock_check
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "lock_exists=true" >> $GITHUB_OUTPUT
          else
            echo "lock_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Remove pnpm-lock.yaml
        if: steps.lock_check.outputs.lock_exists == 'true'
        run: |
          echo "Removing pnpm-lock.yaml to resolve conflicts..."
          rm pnpm-lock.yaml

      - name: Regenerate pnpm-lock.yaml
        run: |
          echo "Regenerating pnpm-lock.yaml..."
          pnpm install --lockfile-only

      - name: Configure git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit lock file changes
        run: |
          git add pnpm-lock.yaml
          if ! git diff --cached --quiet; then
            echo "Committing pnpm-lock.yaml changes..."
            git commit -m "🔒 Regenerate pnpm-lock.yaml to resolve conflicts
            
            Applied by GitHub Action workflow: ${{ github.workflow }}
            Run ID: ${{ github.run_id }}
            Target PR: ${{ github.event.inputs.ref_value }}"
            
            echo "Pushing changes..."
            git push
          else
            echo "No changes to commit after regenerating lock file"
          fi

      - name: Output result
        run: |
          echo "✅ pnpm-lock.yaml has been regenerated and committed"
