name: Production build against CJS/ESM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using Node v14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Build production package and serve it as-if it was a real package
    - run: yarn
    - run: yarn build:prod
    - run: yarn link
    # Node >=13.2.0 enables support for ES modules by default
    # Our default version of node is above 13.2.0
    - run: |
        cd test/esm
        node --version
        sh run.sh
    # Node latest version supports ES modules by default
    - run: |
        cd test/esm
        nvm install node
        node --version
        sh run.sh
    # Node 12.x and >=12.18 enables support for ES modules by default
    - run: |
        cd test/esm
        nvm install 12.18
        node --version
        sh run.sh
    # Node <12.18 requires a flag to support ES modules but can understand them
    - run: |
        cd test/esm
        nvm install 12.17
        node --version
        sh run.sh
    # Node 10 does not understand ES modules
    - run:  |
        cd test/esm
        nvm install 10
        node --version
        sh run.sh
    # Check package score against skypack
    - run: npx @skypack/package-check