name: Publish Version
# Adapted from https://github.com/MylesBorins/node-osc/blob/main/.github/workflows/bump-version.yml

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Type of version'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Using Node v16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Setup Git
      run: |
        git config --local user.name "Nicolas DUBIEN"
        git config --local user.email "github@dubien.org"
    - name: Bump version
      run: npm version ${{github.event.inputs.version}}
    - name: Push main
      run: git push origin main
    - name: Push tag
      run: git push origin $(git describe --tags)
