name: Workflow Security Audit

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - 'next-*_*_*'
      - 'fix-v*'
  push:
    branches:
      - main
      - 'next-*_*_*'
      - 'fix-v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  audit:
    name: 'Audit GitHub Actions workflows'
    if: github.event_name == 'push' || github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened' || (github.event.action == 'labeled' && github.event.label.name == 'force-build-status-execution')
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
